#!/usr/bin/env python3
"""
Test email task implementation for the AI Employee system.
This module provides functionality to handle email-related tasks
for the system, potentially triggered by new files in the incoming/ directory.
"""

import smtplib
import ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
import os
import json
import logging


class EmailTaskHandler:
    """
    Handles email tasks for the AI Employee system.
    """

    def __init__(self, smtp_server=None, smtp_port=None, email_address=None, email_password=None):
        """
        Initialize the email task handler.
        If no SMTP details provided, attempts to read from environment variables.
        """
        self.smtp_server = smtp_server or os.getenv('EMAIL_SMTP_SERVER', 'smtp.gmail.com')
        self.smtp_port = smtp_port or int(os.getenv('EMAIL_SMTP_PORT', '587'))
        self.email_address = email_address or os.getenv('EMAIL_ADDRESS')
        self.email_password = email_password or os.getenv('EMAIL_PASSWORD')

        # Set up logging
        logging.basicConfig(level=logging.INFO)
        self.logger = logging.getLogger(__name__)

    def create_task_notification(self, task_details):
        """
        Create an email notification about a new task.

        Args:
            task_details (dict): Details about the task

        Returns:
            MIMEMultipart: The email message object
        """
        message = MIMEMultipart("alternative")
        message["Subject"] = f"New Task Notification: {task_details.get('objective', 'Task')}"
        message["From"] = self.email_address
        message["To"] = task_details.get("recipient", self.email_address)

        # Create HTML content for the email
        html_content = f"""
        <html>
          <body>
            <h2>New Task Assigned</h2>
            <p><strong>Objective:</strong> {task_details.get('objective', 'N/A')}</p>
            <p><strong>Details:</strong><br>
            {task_details.get('details', 'N/A').replace(chr(10), '<br>')}
            </p>
            <p><strong>Priority:</strong> {task_details.get('priority', 'N/A')}</p>
            <p><strong>Deadline:</strong> {task_details.get('deadline', 'N/A')}</p>
            <p><strong>Approval Required:</strong> {task_details.get('approval_required', 'N/A')}</p>
            <p><em>This notification was generated by the AI Employee system on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</em></p>
          </body>
        </html>
        """

        # Create HTML part
        html_part = MIMEText(html_content, "html")
        message.attach(html_part)

        return message

    def send_test_email(self, recipient="test@example.com", subject="Test Email Task", body="This is a test email."):
        """
        Send a test email to verify email functionality.

        Args:
            recipient (str): Email address of recipient
            subject (str): Subject of the email
            body (str): Body of the email

        Returns:
            bool: True if email was sent successfully, False otherwise
        """
        try:
            # Create the email
            message = MIMEMultipart("alternative")
            message["Subject"] = subject
            message["From"] = self.email_address
            message["To"] = recipient

            # Create both plain text and HTML parts
            text_part = MIMEText(body, "plain")
            html_part = MIMEText(f"<html><body><p>{body}</p></body></html>", "html")

            message.attach(text_part)
            message.attach(html_part)

            # Create secure connection and send email
            context = ssl.create_default_context()

            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls(context=context)
                server.login(self.email_address, self.email_password)
                server.sendmail(self.email_address, recipient, message.as_string())

            self.logger.info(f"Test email sent successfully to {recipient}")
            return True

        except Exception as e:
            self.logger.error(f"Failed to send test email: {str(e)}")
            return False

    def process_incoming_task(self, file_path):
        """
        Process a task file from the incoming directory and send appropriate email notifications.

        Args:
            file_path (str): Path to the task file

        Returns:
            bool: True if processing was successful, False otherwise
        """
        try:
            with open(file_path, 'r') as file:
                content = file.read()

            # Extract task information (simplified - in a real scenario you'd use proper parsing)
            task_data = {
                "file_path": file_path,
                "content": content,
                "timestamp": datetime.now().isoformat()
            }

            # For test purposes, we'll just log the task details
            self.logger.info(f"Processing task from {file_path}")

            # Example: Send a notification email about the new task
            # For this test, we'll just print what would be sent
            self.logger.info(f"Task content: {content[:100]}...")

            return True
        except Exception as e:
            self.logger.error(f"Error processing task file {file_path}: {str(e)}")
            return False


def main():
    """
    Main function to demonstrate the test email task functionality.
    """
    print("Initializing test email task handler...")

    # Create an instance of the email task handler
    email_handler = EmailTaskHandler()

    print("Testing email functionality...")

    # Example task details based on what we found in incoming/
    task_details = {
        "objective": "Create a quarterly report for Q1 2024",
        "details": "Gather sales data from the database\nAnalyze customer feedback\nCreate visualizations\nGenerate executive summary",
        "priority": "High",
        "deadline": "2024-04-01",
        "approval_required": "Yes",
        "recipient": "manager@company.com"
    }

    try:
        # Create a task notification email (without sending it)
        notification = email_handler.create_task_notification(task_details)
        print("Task notification email created successfully")

        # Send a test email if possible
        if email_handler.email_address and email_handler.email_password:
            success = email_handler.send_test_email(
                recipient=email_handler.email_address,
                subject="Test Email Task Notification",
                body="This is a test to verify the email task functionality is working correctly."
            )
            if success:
                print("Test email sent successfully!")
            else:
                print("Failed to send test email. Check your email configuration.")
        else:
            print("Email configuration not found. Set EMAIL_ADDRESS and EMAIL_PASSWORD environment variables to test email sending.")

        # Process files in the incoming directory
        import os
        incoming_dir = "E:/hackathon0/ai-employee/incoming"
        for filename in os.listdir(incoming_dir):
            if filename.endswith('.txt'):
                file_path = os.path.join(incoming_dir, filename)
                email_handler.process_incoming_task(file_path)

        print("Test email task completed.")

    except Exception as e:
        print(f"Error in test email task: {str(e)}")


if __name__ == "__main__":
    main()