#!/usr/bin/env python3
"""
Weekly CEO Briefing Skill
Reads Business_Goals.md, Accounting, Done tasks, and generates Monday Briefing
"""

import os
import json
from datetime import datetime, date, timedelta
from pathlib import Path

class WeeklyCEOBriefing:
    def __init__(self, vault_path="./vault"):
        self.vault_path = Path(vault_path)
        self.business_goals_path = self.vault_path / "Business_Goals.md"
        self.accounting_dir = self.vault_path / "Accounting"
        self.done_dir = self.vault_path / "Done"
        self.briefings_dir = self.vault_path / "Briefings"

    def read_business_goals(self):
        """Read the business goals for strategic context"""
        if self.business_goals_path.exists():
            content = self.business_goals_path.read_text()
            # Extract key goals and metrics
            return {
                "goals_summary": content[:1000],  # First 1000 chars as summary
                "last_updated": self.business_goals_path.stat().st_mtime
            }
        return {"goals_summary": "No business goals defined", "last_updated": None}

    def get_weekly_done_tasks(self):
        """Get tasks completed in the last week"""
        one_week_ago = date.today() - timedelta(days=7)
        done_tasks = []

        for task_file in self.done_dir.glob("*.md"):
            # Check if file was modified in the last week
            mod_date = date.fromtimestamp(task_file.stat().st_mtime)
            if mod_date >= one_week_ago:
                content = task_file.read_text()
                done_tasks.append({
                    "file": task_file.name,
                    "content": content[:500],  # First 500 chars
                    "completed_date": mod_date.isoformat()
                })

        return done_tasks

    def get_financial_summary(self):
        """Get financial summary from accounting directory"""
        financial_summary = {
            "total_transactions": 0,
            "total_amount": 0,
            "categories": {},
            "alerts": []
        }

        # Look for accounting files
        for acc_file in self.accounting_dir.glob("*.md"):
            content = acc_file.read_text()
            # This is a simplified analysis - real implementation would parse financial data
            financial_summary["total_transactions"] += content.count("$")  # Very basic

        return financial_summary

    def generate_briefing(self):
        """Generate the weekly CEO briefing"""
        business_goals = self.read_business_goals()
        done_tasks = self.get_weekly_done_tasks()
        financial_summary = self.get_financial_summary()

        briefing_content = f"""---
title: "Weekly CEO Briefing - {date.today().strftime('%Y-%W')}"
created: {datetime.now().isoformat()}
week: {date.today().isocalendar()[1]}
year: {date.today().year}
status: generated
---

# Weekly CEO Briefing
**Week of {date.today().strftime('%B %d, %Y')}**

## Executive Summary
This week's performance against business objectives. Key highlights and upcoming priorities.

## Business Goals Status
{business_goals['goals_summary']}

### Progress Update
- Goals being actively pursued
- Metrics trending positively
- Areas requiring attention

## Completed Tasks ({len(done_tasks)} this week)
### Summary of Completed Work:
"""

        for i, task in enumerate(done_tasks, 1):
            briefing_content += f"""
#### Task {i}: {task['file']}
- Completed: {task['completed_date']}
- Summary: {task['content'][:200]}...
"""

        briefing_content += f"""
## Financial Summary
- Total Transactions Processed: {financial_summary['total_transactions']}
- Categories Tracked: {len(financial_summary['categories'])}
- Financial Alerts: {len(financial_summary['alerts'])}

## This Week's Impact
- Hours Saved: [Calculated based on task complexity]
- Tasks Automated: [Count of routine tasks handled]
- New Processes Created: [Count of new automations]

## Next Week's Priorities
1. Review and approve pending items
2. Continue progress on strategic goals
3. Monitor financial metrics
4. Address any flagged items

## Recommendations
- [AI-generated recommendations based on data patterns]
- [Suggested optimizations]
- [Potential risks to monitor]

---
*Generated by AI Employee on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""

        # Write briefing to file
        briefing_filename = f"CEO_Briefing_{date.today().strftime('%Y-%m-%d')}.md"
        briefing_path = self.briefings_dir / briefing_filename
        briefing_path.write_text(briefing_content)

        print(f"Weekly CEO Briefing generated: {briefing_path.name}")
        return briefing_path

    def run(self):
        """Main execution method"""
        print(f"Weekly CEO Briefing generator starting at {datetime.now()}")

        # Ensure briefings directory exists
        self.briefings_dir.mkdir(parents=True, exist_ok=True)

        briefing_path = self.generate_briefing()
        print(f"CEO Briefing created: {briefing_path}")

if __name__ == "__main__":
    briefing_generator = WeeklyCEOBriefing()
    briefing_generator.run()